name: 🚀 Деплой в Yandex Cloud

# Запуск при пуше в ветку main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🔧 Выполнить развертывание
    runs-on: ubuntu-latest

    steps:
      # 1. Получить код из репозитория
      - name: 📦 Получить код
        uses: actions/checkout@v4

      # 2. Установить YC CLI
      - name: 🔧 Установить YC CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/.yc/bin" >> $GITHUB_PATH

      # 3. Настроить профиль Yandex Cloud с помощью сервисного аккаунта
      - name: 🔐 Настроить доступ к Yandex Cloud
        uses: yandex-cloud/actions/configure@v1
        with:
          cloud-id: ${{ secrets.YC_CLOUD_ID }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          key-id: ${{ secrets.YC_SERVICE_ACCOUNT_KEY_ID }}
          service-account-key: ${{ secrets.YC_SERVICE_ACCOUNT_SECRET_KEY }}

      # 4. Проверить, что всё работает — получить список ВМ
      - name: 🖥️ Показать список виртуальных машин
        run: yc compute instance list

      # 🔥 Пример: Деплой простого приложения (Node.js)
      # Раскомментируйте, если нужно собрать и запустить приложение

      # - name: Установить Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'

      # - name: Установить зависимости
      #   run: npm install

      # - name: Собрать приложение
      #   run: npm run build

      # - name: Загрузить на ВМ или в Functions (пример ниже)
      #   run: yc serverless function version create --name my-function --runtime nodejs18 --entrypoint index.handler --memory 256m --source-path ./dist

      # 🌐 Или: Деплой статики в Object Storage (s3)
      # - name: Загрузить статику в Storage
      #   run: |
      #     yc storage cp --recursive dist/* s3://your-bucket-name/

      # 🧪 Пример: Запустить тесты
      - name: 🧪 Запустить тесты
        run: echo "Тесты запущены!"
